services:
  - type: web
    name: yt-automation-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: uvicorn main_minimal:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true 